### ISSUE TITLE
Make the hadoop version a variable and make the spark version variable just a number

### ISSUE THREAD

**Issue by vforgione** [5thColumn/ansible-role-spark#3]
I think a better way to do this would be

```yaml
spark_version: 2.1.0
hadoop_version: 2.7
spark_folder: "spark-{{ spark_version }}-bin-hadoop{{ hadoop_version }}"
```

https://github.com/Prajaktcs/ansible-role-spark/blob/master/defaults/main.yml#L4-L6
